public with sharing class TransactionService{

    public static void categorizeTransactions(List<InputTransaction> inputTransactions){
        
    }

    public static void addTransactions(List<TransactionService.InputTransaction> inputTransactions){

    }


    public class InputTransaction{
        String bank;
        String description;
        String Category;
        String SubCategory;
        Double Amount;
    }
}